function help   {

    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo_clrd 1 32 "HELP START"
    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo_clrd 1 32 "- Test Environment"
    echo_clrd 1 33 "    - scenario description"
    echo_clrd 1 33 "        1. option is '--public-intgrm local'"
    echo_clrd 1 33 "            - 'github' is simulated by a local folder"
    echo_clrd 1 33 "        2. option is '--public-dvlpr real'"
    echo_clrd 1 33 "            - 'developer' repos are real, true"
    echo_clrd 1 33 "        3. option '--create-local-public-repos'"
    echo_clrd 1 33 "            - create the public local repository if it does not exist"
    echo_clrd 1 33 "    - command:"
    echo_clrd 1 35 "        $main_script --public-intgrm local --public-dvlpr real --create-local-public-repos"
    echo_clrd 1 33 "    - what does command do:"
    echo_clrd 1 33 "        - perform the following command"
    echo_clrd 1 34 "            $current_script_dir/repos_sync.sh --publc \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_reale/remote/public/https/github/<module name>.git\" --dvlpr \"file:///Volumes/mypass2/ObsiDataRemote/Year_2023/repo__prjs/<module name>.git\" --rel-name First_Release --rel-null 1 3  --rel-inc 2"
    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo_clrd 1 32 "- Real Environment"
    echo_clrd 1 33 "    - scenario description"
    echo_clrd 1 33 "        1. option is '--public-intgrm github'"
    echo_clrd 1 33 "            - 'github' is not simulated"
    echo_clrd 1 33 "        2. option is '--public-dvlpr real'"
    echo_clrd 1 33 "            - 'developer' repos are real, true"
    echo_clrd 1 33 "    - command:"
    echo_clrd 1 33 "        ${BASH_SOURCE[0]} --public-intgrm github --public-dvlpr real"
    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 35 "            $ ${BASH_SOURCE[0]} --env-publc-remote \"github\" \"Module_02\""
##    echo_clrd 1 33 "    --env-dvlpr-remote"
##    echo_clrd 1 33 "        ${BASH_SOURCE[0]} --env-dvlpr-remote <root folder of repos> <project/module name>"
##    echo_clrd 1 35 "            $ ${BASH_SOURCE[0]} --env-dvlpr-remote \"mypass2_repo\" \"Module_02\""
##    echo_clrd 1 33 "    --env-dvlpr"
##    echo_clrd 1 33 "        ${BASH_SOURCE[0]} --env-dvlpr <root folder of repos> <project/module name> <command>"
##    echo_clrd 1 35 "            $ ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_02\" <command>"
##    echo_clrd 1 33 "        ~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 33 "        <command> description:"
##    echo_clrd 1 33 "        ~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 33 "        - remote_config"
##    echo_clrd 1 33 "            - remote_config:<root folder of remote repos>"
##    echo_clrd 1 35 "                $ ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_02\" remote_config:mypass2_repo"
##    echo_clrd 1 34 "                $ git remote add my_public_repo \"file://<remote_repo_path>\""
##    echo_clrd 1 33 "            - remote_config:remove"
##    echo_clrd 1 35 "                $ ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_02\" remote_config:remove"
##    echo_clrd 1 34 "                $ git remote remove my_public_repo"
##    echo_clrd 1 33 "            - remote_config:public:<root folder of remote repos>"
##    echo_clrd 1 35 "                $ ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws2\" \"Module_02\" remote_config:public:github"
##    echo_clrd 1 34 "                $ git remote add https_public_repo \"file://<remote_repo_path>\""
##    echo_clrd 1 33 "            - remote_config:public:remove"
##    echo_clrd 1 35 "                $ ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws2\" \"Module_02\" remote_config:public:remove"
##    echo_clrd 1 34 "                $ git remote add https_public_repo"
##    echo_clrd 1 33 "        - git"
##    echo_clrd 1 33 "            - git:status"
##    echo_clrd 1 34 "                $ git status"
##    echo_clrd 1 33 "            - git:add"
##    echo_clrd 1 34 "                $ git add ."
##    echo_clrd 1 33 "            - git:log"
##    echo_clrd 1 34 "                $ git logpretty"
##    echo_clrd 1 33 "            - git:remote"
##    echo_clrd 1 34 "                $ git remote"
##    echo_clrd 1 33 "            - git:commit"
##    echo_clrd 1 34 "                $ git add ."
##    echo_clrd 1 34 "                $ git commit -m \"Standard message\""
##    echo_clrd 1 33 "                - commit:<commit message>"
##    echo_clrd 1 34 "                    $ git add ."
##    echo_clrd 1 34 "                    $ git commit -m \"<commit message>\""
##    echo_clrd 1 33 "            - git:push"
##    echo_clrd 1 34 "                $ git push"
##    echo_clrd 1 33 "                - push:set-upstream"
##    echo_clrd 1 34 "                    $ git push --set-upstream my_public_repo main"
##    echo_clrd 1 33 "                    - push:set-upstream:public"
##    echo_clrd 1 34 "                        $ git push --set-upstream https_public_repo main"
##    echo_clrd 1 33 "                - push:public"
##    echo_clrd 1 34 "                    $ git push https_public_repo main"
##    echo_clrd 1 33 "        - upd_files"
##    echo_clrd 1 33 "            - upd_files:commit"
##    echo_clrd 1 34 "                $ git add ."
##    echo_clrd 1 34 "                $ git commit -m \"Standard message\""
##    echo_clrd 1 33 "            - upd_files:commit:<commit message>"
##    echo_clrd 1 34 "                $ git add ."
##    echo_clrd 1 34 "                $ git commit -m \"<commit message>\""
##    echo_clrd 1 33 "            - upd_files:commit:push"
##    echo_clrd 1 34 "                $ git add ."
##    echo_clrd 1 34 "                $ git commit -m \"Standard message\""
##    echo_clrd 1 34 "                $ git push"
##    echo_clrd 1 33 "            - upd_files:commit:<commit message>:push"
##    echo_clrd 1 34 "                $ git add ."
##    echo_clrd 1 34 "                $ git commit -m \"<commit message>\""
##    echo_clrd 1 34 "                $ git push"
##    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 32 "- Integration Manager commands: synchronization & check commands"
##    echo_clrd 1 33 "    - synchro and check commands & their common options"
##    echo_clrd 1 33 "        - --scn-intgrm <integration scenario name>"
##    echo_clrd 1 33 "        - --ws-intgrm <integration manager workstation name>"
##    echo_clrd 1 33 "        - --ws-intgrm <integration manager name>"
##    echo_clrd 1 33 "    - synchro commands & its options"
##    echo_clrd 1 33 "        - ${BASH_SOURCE[0]} --publc \"<url public repository>\" --dvlpr \"<url public developer repository>\" --rel-name <release name> --rel-null [<release field position> ...] --rel-inc [<release field position> ...]"
##    echo_clrd 1 33 "            - \"Test scenario\" example"
##    echo_clrd 1 35 "                - ${BASH_SOURCE[0]} --publc \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/public/https/github/Module_02.git\" --dvlpr \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/developer/mypass2_repo/Module_02.git\" --rel-name First_Release --rel-null 1 3  --rel-inc 2"
##    echo_clrd 1 33 "            - \"Real scenario\" example"
##    echo_clrd 1 35 "                - ${BASH_SOURCE[0]} --publc \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/public/https/github/Module_02.git\" --dvlpr \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/developer/mypass2_repo/Module_02.git\" --rel-name First_Release --rel-null 1 3  --rel-inc 2"
##    echo_clrd 1 33 "    - check commands & its options"
##    echo_clrd 1 33 "        --env-intgrm"
##    echo_clrd 1 33 "            ${BASH_SOURCE[0]} --scn-intgrm <scenario name> --ws-intgrm <workstation name> --env-intgrm <project/module name> <command>"    
##    echo_clrd 1 35 "                ${BASH_SOURCE[0]} --scn-intgrm reale --ws-intgrm ws1 --env-intgrm \"mpfw_code_apps_tst_20221206\" <command>"
##    echo_clrd 1 33 "            ~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 33 "            <command> description:"
##    echo_clrd 1 33 "            ~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 33 "            - git"
##    echo_clrd 1 33 "                - git:status"
##    echo_clrd 1 34 "                    $ git status"
##    echo_clrd 1 33 "                - git:log"
##    echo_clrd 1 34 "                    $ git logpretty"
##    echo_clrd 1 33 "                - git:remote"
##    echo_clrd 1 34 "                    $ git remote"
##    echo_clrd 1 33 "                - git:push"
##    echo_clrd 1 34 "                    $ git remote"
##    echo_clrd 1 33 "                - git:push"
##    echo_clrd 1 34 "                    $ git push github github_main:main"
##    echo_clrd 1 33 "                    - push:set-upstream"
##    echo_clrd 1 34 "                        $ git push --set-upstream github github_main:main"
##    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 32 "- Command sequence to prepare the test environment"
##    echo_clrd 1 33 "    - step 1: repositories creation"
##    echo_clrd 1 33 "        - remote"
##    echo_clrd 1 33 "            - public \"github simulation\""
##    echo_clrd 1 35 "                ${BASH_SOURCE[0]} --env-publc-remote \"github\" \"Module_xx\""
##    echo_clrd 1 34 "                N.B.: the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/public/https/<1st par>/<2nd par>.git\""
##    echo_clrd 1 31 "                      the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/public/https/github/Module_xx.git\""
##    echo_clrd 1 33 "            - public developer \"mypass2 simulation\""
##    echo_clrd 1 35 "                ${BASH_SOURCE[0]} --env-dvlpr-remote \"mypass2_repo\" \"Module_xx\""
##    echo_clrd 1 34 "                N.B.: the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/developer/<1st par>/<2nd par>.git\""
##    echo_clrd 1 31 "                      the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/developer/mypass2_repo/Module_xx.git\""
##    echo_clrd 1 33 "        - local"
##    echo_clrd 1 33 "            - main developer"
##    echo_clrd 1 33 "                - scope: to simulate the developer repository with all its branches"
##    echo_clrd 1 33 "                - example"
##    echo_clrd 1 35 "                    ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\""
##    echo_clrd 1 34 "                    N.B.: the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/developers/<1st par>/<2nd par>\""
##    echo_clrd 1 31 "                          the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/developers/dvlpr1_ws1/Module_xx\""
##    echo_clrd 1 33 "            - service developer"
##    echo_clrd 1 33 "                - scope: (OPTIONAL) to create a NOT-empty \"remote public\" repository; it wll track the remote public branch \"main\"; see its remote configuration"
##    echo_clrd 1 33 "                - example"
##    echo_clrd 1 35 "                    ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws2\" \"Module_xx\""
##    echo_clrd 1 34 "                    N.B.: the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/developers/<1st par>/<2nd par>\""
##    echo_clrd 1 31 "                          the path of repo is \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/developers/dvlpr1_ws2/Module_xx\""
##    echo_clrd 1 33 "    - step 2: local repositories configuration: 'git remote add <remote repository>'"
##    echo_clrd 1 33 "        - local MAIN developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" remote_config:mypass2_repo"
##    echo_clrd 1 35 "                (to check the previous command) ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" git:remote"
##    echo_clrd 1 33 "        - (OPTIONAL) local SERVICE developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws2\" \"Module_xx\" remote_config:public:github"
##    echo_clrd 1 33 "    - step 3: local repositories first commit"
##    echo_clrd 1 33 "        - local MAIN developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" upd_files:commit:First_commit"
##    echo_clrd 1 35 "                (to check the previous command) ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" git:log"
##    echo_clrd 1 33 "        - (OPTIONAL) local SERVICE developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws2\" \"Module_xx\" upd_files:commit:First_commit_from_developer"
##    echo_clrd 1 33 "    - step 4: local repositories first push"
##    echo_clrd 1 33 "        - local MAIN developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" git:push:set-upstream"
##    echo_clrd 1 35 "                (to check the previous command) ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" git:log"
##    echo_clrd 1 33 "        - (OPTIONAL) local SERVICE developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws2\" \"Module_xx\" git:push:set-upstream:public"
##    echo_clrd 1 33 "    - step 5: local main repository update (next commits & pushes)"
##    echo_clrd 1 33 "        - local MAIN developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" upd_files:commit:Second_commit:push"
##    echo_clrd 1 35 "                (to check the previous command) ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws1\" \"Module_xx\" git:log"
##    echo_clrd 1 33 "        - (OPTIONAL) local SERVICE developer repo"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --env-dvlpr \"dvlpr1_ws2\" \"Module_xx\" upd_files:commit:Second_commit_from_developer:push"
##    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
##    echo_clrd 1 32 "- Command sequence to synchronize \"github\" public repository with the \"developer\" public one"
##    echo_clrd 1 32 "    - default scenario (the default option are: --scn-intgrm 1 --ws-intgrm ws2)"
##    echo_clrd 1 33 "        ${BASH_SOURCE[0]} --publc \"<repo of step_1, remote public (github simulation)>\" --dvlpr \"<repo of step_1, remote public developer (mypass2 simulation)>\" --rel-name First_Release --rel-null 1 3  --rel-inc 2"
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --publc \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/public/https/github/Module_xx.git\" --dvlpr \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/developer/mypass2_repo/Module_xx.git\" --rel-name First_Release --rel-null 1 3  --rel-inc 2"
##    echo_clrd 1 35 "                (to check the previous command) ${BASH_SOURCE[0]} --env-intgrm \"Module_xx\" git:log"
##    echo_clrd 1 32 "    - NOT default scenario (example options are: --scn-intgrm reale --ws-intgrm ws1)"
##    echo_clrd 1 33 "        ${BASH_SOURCE[0]} --scn-intgrm <scenario  name> --ws-intgrm <workstation name> --publc \"<repo of step_1, remote public (github simulation)>\" --dvlpr \"<repo of step_1, remote public developer (mypass2 simulation)>\" --rel-name First_Release --rel-null 1 3  --rel-inc 2"
##    echo_clrd 1 31 "            N.B.: you have to create the folder \"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_<scenario name>/manager/intgrm_<workstation name>\""
##    echo_clrd 1 35 "                (to check the existence of integration manager folder) intgrm_folder=\"$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_reale/manager/intgrm_ws1\"; [ -d \"\$intgrm_folder\" ] && echo \"the folder exists\" || mkdir \"\$intgrm_folder\" "
##    echo_clrd 1 35 "            ${BASH_SOURCE[0]} --scn-intgrm reale --ws-intgrm ws1 --publc \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/public/https/github/Module_xx.git\" --dvlpr \"file://$HOME/ObsiData/distributed_git/integration_manager_workflow/scenario_1/remote/developer/mypass2_repo/Module_xx.git\" --rel-name First_Release --rel-null 1 3  --rel-inc 2"
##    echo_clrd 1 35 "                (to check the previous command) ${BASH_SOURCE[0]} --scn-intgrm reale --ws-intgrm ws1 --env-intgrm \"Module_xx\" git:log"
    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo_clrd 1 32 "HELP END"
    echo_clrd 1 32 "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

}
